version: '3.8'

services:
  mcp-calculadora:
    build: .
    container_name: mcp_integrales_container
    ports:
      - "8000:8000"
    volumes:
      # Sincroniza los archivos en tiempo real y guarda los reportes HTML generados en tu máquina local
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - MPLBACKEND=Agg
    restart: unless-stopped