diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=schannel
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=Jefferson Piero
user.email=jefferson.vilcapoma@unmsm.edu.pe
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/RAC-UNMSM/laboratory-cc.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
branch.main.vscode-merge-base=origin/main
branch.grupo02.remote=origin
branch.grupo02.merge=refs/heads/grupo02
branch.grupo02.vscode-merge-base=origin/grupo02
branch.grupo02-jefferson-test1.vscode-merge-base=origin/grupo02
branch.integrantes.vscode-merge-base=origin/main
branch.grupo02-Jefferson-Vilcapoma-Pariona.vscode-merge-base=origin/main
